name: jedi-linear
channels:
  - conda-forge
dependencies:
  - 'python=3.13.*'
  - pip
  - verilator
  - pip:
    - da4ml < 0.5
    - h5py
    - HGQ2
    - jax
    - keras
    - matplotlib
    - mplhep
    - numpy
    - omegaconf
    - tqdm
